### ISSUE TITLE
Es6 classes

### ISSUE THREAD

**Issue by aslanovsergey** [ryanelian/ts-polyfill#2]
Hi,

Which package I need to import to transpile ES6 classes?

**Comment by ryanelian** [comment]
Hello, what do you mean transpile ES6 classes?

This project is a runtime polyfill for TypeScript, not a transpiler.

If you need just a transpiler, try using Babel or TypeScript.

If you happened to need a full web application project bundler + transpiler, try using https://github.com/ryanelian/instapack (`ipack new empty` then `ipack` then reference the build output in your `.html`)

**Comment by aslanovsergey** [comment]
I meant polyfill Es6 classes. And especially i'm interested how to do it for dependencies

**Comment by ryanelian** [comment]
You are confusing syntax with polyfills.

A class cannot be polyfilled, only compiled with TypeScript or Babel, because it is a syntax sugar for function.

For example, a transpiled Class using TypeScript:

![image](https://user-images.githubusercontent.com/8892187/54179133-78116800-44ca-11e9-88d6-e691fa0530a9.png)

A polyfill allows you to use methods not available in your browser:

For example:

```
let p = new Promise(function(accept, reject){
});
```

The above `Promise` method call is recognized as ES5 code but may not run in browsers not implementing ES 2015 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise i.e. Internet Explorer)

However, with `Promise` polyfill, you will be able to use `Promise` in IE. But there's no way to make IE recognize `class` or `async-await` syntax.
